# Generated by Django 5.0.4 on 2024-05-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_comments_author_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("back-end", "Back-end"),
                    ("front-end", "Front-end"),
                    ("ios", "iOS"),
                    ("android", "Android"),
                ],
                max_length=9,
            ),
        ),
    ]
