# Generated by Django 5.0.4 on 2024-04-12 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0002_user_can_be_contacted_user_can_data_be_shared_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthdate",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
